#设置环境
server:
  port: 8083

spring:
  #允许循环引用
  main:
    allow-circular-references: true
  application:
    name: transaction-service
  profiles:
    include: local

  # 数据库配置
  datasource:
    url: jdbc:mysql://39.101.207.21:3306/transaction_service?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: Yj20o48zLkCwI1h
    type: com.alibaba.druid.pool.DruidDataSource

    #数据库连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis配置
  redis:
    host: ${host.redis.ip}
    port: 6379
    password: ${host.redis.pwd}

  cloud:
      #配置中心
    loadbalancer:
      ribbon:
        enabled: false

#mybatisplus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
    #输出数据库操作log
logging:
  level:
    com.zhang: debug
  ##pattern:
    ##dateformat: HH:mm:ss:SSS
  #file:
    #path: "logs/${spring.application.name}"


